# Generated by Django 5.2.6 on 2025-10-02 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='seat',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seat',
            name='booked_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
        ),
        migrations.AddField(
            model_name='seat',
            name='booked_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.seat', unique=True),
        ),
    ]
