# Generated by Django 5.2.6 on 2025-10-02 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_booking_date_remove_booking_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='booked_date',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='booked_movie',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='booked_user',
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
